# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# jd_joy_feedPets,jd_joy_steal,jd_daily_egg,jd_superMarket
name:  合集-宠汪汪喂食&偷狗粮&天天提鹅&东东超市

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: joy_feedPets
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/nbzongzong/jd_scripts1207.git ~/scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: '运行 【宠汪汪喂食&偷狗粮&天天提鹅&东东超市】'
        run: |
          cd  ~/scripts
          npm install
          node jd_joy_feedPets.js
          node jd_joy_steal.js
          node jd_daily_egg.js
          node jd_superMarket.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          JOY_FEED_COUNT: ${{ secrets.JOY_FEED_COUNT }}
          JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED }}
          SUPERMARKET_UPGRADE: ${{ secrets.SUPERMARKET_UPGRADE }}
          BUSINESS_CIRCLE_JUMP: ${{ secrets.BUSINESS_CIRCLE_JUMP }}
          SUPERMARKET_LOTTERY: ${{ secrets.SUPERMARKET_LOTTERY }}
          SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES }}
          #微信酱
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          #BARK推送
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          #tg推送
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          #钉钉推送
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          #企业微信推送
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          #iGot推送
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          #酷推(Cool Push)推送
          QQ_SKEY: ${{ secrets.QQ_SKEY }}
          QQ_MODE: ${{ secrets.QQ_MODE }}
                    #pushplus推送
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
